export const data = {
    id: 1,
    fName: 'scott',
    lName: 'comeaux',
    favoriteThings: [
        {
            favoriteThingsid: 1,
            computer: {
                lol:'league', 
                yt:'youtube', 
                code:'programming',
                thingsToBreak: {
                    random: 'rand',
                    testable: 'test',
                    reallyBreaking: {
                        item1: 'one',
                        item2: 'two',
                        breakMe: {
                            broke: 'broken',
                            plzBreak: 'plz',
                            isItBroken: 'unsure If this is what I want.. lol',
                            bans: [
                                {
                                    "championId": 122,
                                    "pickTurn": 1
                                },
                                {
                                    "championId": 67,
                                    "pickTurn": 2
                                }
                            ]
                        }
                    }
                }
            }
        }
    ],
    participants: [
        {
            "championId": 18,
            "participantId": 1,
            "spell1Id": 4,
            "spell2Id": 7,
            "stats": {
                "assists": 10,
                "champLevel": 15,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 8221,
                "damageDealtToTurrets": 4967,
                "damageSelfMitigated": 12387,
                "deaths": 9,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 13965,
                "goldSpent": 11950,
                "inhibitorKills": 0,
                "item0": 1055,
                "item1": 3006,
                "item2": 3095,
                "item3": 3094,
                "item4": 3072,
                "item5": 1043,
                "item6": 3340,
                "killingSprees": 3,
                "kills": 10,
                "largestCriticalStrike": 662,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 347,
                "magicDamageDealt": 34108,
                "magicDamageDealtToChampions": 4788,
                "magicalDamageTaken": 7498,
                "neutralMinionsKilled": 18,
                "neutralMinionsKilledEnemyJungle": 4,
                "neutralMinionsKilledTeamJungle": 9,
                "objectivePlayerScore": 0,
                "participantId": 1,
                "pentaKills": 0,
                "perk0": 8005,
                "perk0Var1": 2282,
                "perk0Var2": 1016,
                "perk0Var3": 1266,
                "perk1": 9111,
                "perk1Var1": 1203,
                "perk1Var2": 400,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 12,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 540,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 10,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 28,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "physicalDamageDealt": 113175,
                "physicalDamageDealtToChampions": 19102,
                "physicalDamageTaken": 15819,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 9,
                "totalDamageDealt": 149153,
                "totalDamageDealtToChampions": 24737,
                "totalDamageTaken": 24637,
                "totalHeal": 3568,
                "totalMinionsKilled": 162,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 111,
                "totalUnitsHealed": 3,
                "tripleKills": 0,
                "trueDamageDealt": 1869,
                "trueDamageDealtToChampions": 847,
                "trueDamageTaken": 1320,
                "turretKills": 1,
                "unrealKills": 0,
                "visionScore": 11,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 0,
                "wardsPlaced": 8,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 4.9,
                    "10-20": 5.7,
                    "20-30": 5.6
                },
                "csDiffPerMinDeltas": {
                    "0-10": -0.34999999999999987,
                    "10-20": 0.25000000000000044,
                    "20-30": 1.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -204.2,
                    "10-20": 266.6000000000001,
                    "20-30": 446.59999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 400.9,
                    "10-20": 1059.3,
                    "20-30": 767
                },
                "goldPerMinDeltas": {
                    "0-10": 328.5,
                    "10-20": 559.8,
                    "20-30": 447
                },
                "lane": "BOTTOM",
                "participantId": 1,
                "role": "DUO_CARRY",
                "xpDiffPerMinDeltas": {
                    "0-10": 59.599999999999994,
                    "10-20": -13.050000000000011,
                    "20-30": 72.25
                },
                "xpPerMinDeltas": {
                    "0-10": 303.4,
                    "10-20": 508.1,
                    "20-30": 571.8
                }
            }
        },
        {
            "championId": 38,
            "participantId": 2,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "assists": 6,
                "champLevel": 14,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 3713,
                "damageDealtToTurrets": 1004,
                "damageSelfMitigated": 18288,
                "deaths": 8,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 10257,
                "goldSpent": 9025,
                "inhibitorKills": 0,
                "item0": 2033,
                "item1": 3157,
                "item2": 3040,
                "item3": 3047,
                "item4": 1058,
                "item5": 0,
                "item6": 3340,
                "killingSprees": 2,
                "kills": 6,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 468,
                "magicDamageDealt": 69820,
                "magicDamageDealtToChampions": 10777,
                "magicalDamageTaken": 9693,
                "neutralMinionsKilled": 8,
                "neutralMinionsKilledEnemyJungle": 0,
                "neutralMinionsKilledTeamJungle": 5,
                "objectivePlayerScore": 0,
                "participantId": 2,
                "pentaKills": 0,
                "perk0": 8021,
                "perk0Var1": 2334,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 3533,
                "perk1Var2": 500,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 15,
                "perk2Var2": 50,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 372,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 829,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 2547,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "physicalDamageDealt": 15265,
                "physicalDamageDealtToChampions": 1018,
                "physicalDamageTaken": 12960,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5003,
                "timeCCingOthers": 13,
                "totalDamageDealt": 85958,
                "totalDamageDealtToChampions": 12435,
                "totalDamageTaken": 22886,
                "totalHeal": 5752,
                "totalMinionsKilled": 136,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 108,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 871,
                "trueDamageDealtToChampions": 639,
                "trueDamageTaken": 232,
                "turretKills": 1,
                "unrealKills": 0,
                "visionScore": 8,
                "visionWardsBoughtInGame": 1,
                "wardsKilled": 0,
                "wardsPlaced": 6,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 5.9,
                    "10-20": 3.5,
                    "20-30": 4.1
                },
                "csDiffPerMinDeltas": {
                    "0-10": -1.5999999999999999,
                    "10-20": -1.4,
                    "20-30": -1.0999999999999996
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 140.69999999999996,
                    "10-20": -290.5,
                    "20-30": -452.30000000000007
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 372,
                    "10-20": 957.6,
                    "20-30": 757.4
                },
                "goldPerMinDeltas": {
                    "0-10": 257,
                    "10-20": 298.5,
                    "20-30": 400
                },
                "lane": "MIDDLE",
                "participantId": 2,
                "role": "SOLO",
                "xpDiffPerMinDeltas": {
                    "0-10": -47.900000000000034,
                    "10-20": -224.5,
                    "20-30": -94.99999999999997
                },
                "xpPerMinDeltas": {
                    "0-10": 403.7,
                    "10-20": 301.7,
                    "20-30": 525.4
                }
            }
        }
    ],
    last: 'finalItem'
}