export const mockData = {
    "gameDuration": 1856,
    "gameId": 3462156980,
    "id": 1,
    "participantAccountInfo": [
        {
            "participantId": 1,
            "player": {
                "accountId": "qUgBfG8cOklW0PlWex_fhQ3tNAz4MKFUIl83FECzDrb0uThR0XS4KioF",
                "currentAccountId": "qUgBfG8cOklW0PlWex_fhQ3tNAz4MKFUIl83FECzDrb0uThR0XS4KioF",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/2164261352459200",
                "platformId": "NA1",
                "profileIcon": 905,
                "summonerId": "6LTs7LLcVDkKhTPS3DqDnRWqWHxZ-YTWTi9ttXcR_e160slP",
                "summonerName": "Major Jg Diff"
            }
        },
        {
            "participantId": 2,
            "player": {
                "accountId": "1GZU4mgkdZeYNcTl197uwYP2C43SzhaHfpqDvhVUoUrSA4A",
                "currentAccountId": "1GZU4mgkdZeYNcTl197uwYP2C43SzhaHfpqDvhVUoUrSA4A",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/238797543",
                "platformId": "NA1",
                "profileIcon": 3790,
                "summonerId": "hHaj3LAfu6h43AN924Gvj9nbAxdXyvoeyBN9fQsHF_sytiU",
                "summonerName": "joaquim sanders"
            }
        },
        {
            "participantId": 3,
            "player": {
                "accountId": "yz2SY0QoGhDnSWz_Z_HTZSmJSnq-juHppU7ttc6gzmjbGBI",
                "currentAccountId": "yz2SY0QoGhDnSWz_Z_HTZSmJSnq-juHppU7ttc6gzmjbGBI",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/205681229",
                "platformId": "NA1",
                "profileIcon": 4622,
                "summonerId": "adEv0V8EIGBkTsiFNShNs-TaqHtg1sb2Qd3gb50xFAP30dE",
                "summonerName": "Anth\u00f8ne"
            }
        },
        {
            "participantId": 4,
            "player": {
                "accountId": "xYrwKymEP_sPMMAuZw_HOoGT1-CZA6T_GLnxYPpj786xaxI",
                "currentAccountId": "xYrwKymEP_sPMMAuZw_HOoGT1-CZA6T_GLnxYPpj786xaxI",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/234014976",
                "platformId": "NA1",
                "profileIcon": 1151,
                "summonerId": "-TEkbjkHe8X_7moPtoU08zu2ohVAkP3CQSDKJhEbiSpwDNU",
                "summonerName": "black big daddy"
            }
        },
        {
            "participantId": 5,
            "player": {
                "accountId": "46bLDyGCWthcSi5dXD8BQlKRYgs9GcXdzmCrrgP5Ff5fOL8",
                "currentAccountId": "46bLDyGCWthcSi5dXD8BQlKRYgs9GcXdzmCrrgP5Ff5fOL8",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/223306910",
                "platformId": "NA1",
                "profileIcon": 661,
                "summonerId": "JhXuHsepXeDSEqlUszd3p6F0zeNNdAKXylBKcp0SPFNaeVk",
                "summonerName": "Support on Kush"
            }
        },
        {
            "participantId": 6,
            "player": {
                "accountId": "yUJAbemA7z3iwCPOs1CsoDTbttvpChCpYvFE6Cqr1erISWI",
                "currentAccountId": "yUJAbemA7z3iwCPOs1CsoDTbttvpChCpYvFE6Cqr1erISWI",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/201510845",
                "platformId": "NA1",
                "profileIcon": 3587,
                "summonerId": "aRnXezVcGVcFowjqMSVdgbg9S8RKgascRx1MVB16g2qZlHY",
                "summonerName": "MasterYodi"
            }
        },
        {
            "participantId": 7,
            "player": {
                "accountId": "t9H6GR51XniTfA-Ea6sCRvARufMlJK0_TlJxVxBsEXBNCl4",
                "currentAccountId": "t9H6GR51XniTfA-Ea6sCRvARufMlJK0_TlJxVxBsEXBNCl4",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/227523009",
                "platformId": "NA1",
                "profileIcon": 741,
                "summonerId": "4anz14djeXCWJmSxDgMJ0-JZsvfmDlmHmvWsgiHo0zpfk18",
                "summonerName": "Kushhy"
            }
        },
        {
            "participantId": 8,
            "player": {
                "accountId": "YRRQ0McloGSx_Mwi6m0LRRu0J_n9QDlQ9X50WZ6fDY5ssr--f2UBFmvB",
                "currentAccountId": "YRRQ0McloGSx_Mwi6m0LRRu0J_n9QDlQ9X50WZ6fDY5ssr--f2UBFmvB",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/2426354516232672",
                "platformId": "NA1",
                "profileIcon": 23,
                "summonerId": "c1acOWhY2A71TFGr2gf8Hf8yXXP0tukMeQh721px7jxE8eyo",
                "summonerName": "Qtr Troll King "
            }
        },
        {
            "participantId": 9,
            "player": {
                "accountId": "YWvJFu7eYUcQ2hAUFRSFMMVl5I7_ri4AUFOJ81lMAfBdDw",
                "currentAccountId": "YWvJFu7eYUcQ2hAUFRSFMMVl5I7_ri4AUFOJ81lMAfBdDw",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/44502856",
                "platformId": "NA1",
                "profileIcon": 1228,
                "summonerId": "BVi39_4VCMn3SgT9r65qJlVDbq8ix2tKPsIKeJpuV59L8N4",
                "summonerName": "Learn2Program"
            }
        },
        {
            "participantId": 10,
            "player": {
                "accountId": "_HJRk7sg3m4InBpFKyZWZ4-FC-5JMGivEG4n_SkiQ1yMFl4",
                "currentAccountId": "_HJRk7sg3m4InBpFKyZWZ4-FC-5JMGivEG4n_SkiQ1yMFl4",
                "currentPlatformId": "NA1",
                "matchHistoryUri": "/v1/stats/player_history/NA1/239257371",
                "platformId": "NA1",
                "profileIcon": 3382,
                "summonerId": "ch8AQ0ckl3RLoKO_p6h4kcQX6dlOrP_YnCX_dcO0TE5l2YM",
                "summonerName": "ahgasaearmy"
            }
        }
    ],
    "participants": [
        {
            "championId": 18,
            "participantId": 1,
            "spell1Id": 4,
            "spell2Id": 7,
            "stats": {
                "assists": 10,
                "champLevel": 15,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 8221,
                "damageDealtToTurrets": 4967,
                "damageSelfMitigated": 12387,
                "deaths": 9,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 13965,
                "goldSpent": 11950,
                "inhibitorKills": 0,
                "item0": 1055,
                "item1": 3006,
                "item2": 3095,
                "item3": 3094,
                "item4": 3072,
                "item5": 1043,
                "item6": 3340,
                "killingSprees": 3,
                "kills": 10,
                "largestCriticalStrike": 662,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 347,
                "magicDamageDealt": 34108,
                "magicDamageDealtToChampions": 4788,
                "magicalDamageTaken": 7498,
                "neutralMinionsKilled": 18,
                "neutralMinionsKilledEnemyJungle": 4,
                "neutralMinionsKilledTeamJungle": 9,
                "objectivePlayerScore": 0,
                "participantId": 1,
                "pentaKills": 0,
                "perk0": 8005,
                "perk0Var1": 2282,
                "perk0Var2": 1016,
                "perk0Var3": 1266,
                "perk1": 9111,
                "perk1Var1": 1203,
                "perk1Var2": 400,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 12,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 540,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 10,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 28,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "physicalDamageDealt": 113175,
                "physicalDamageDealtToChampions": 19102,
                "physicalDamageTaken": 15819,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 9,
                "totalDamageDealt": 149153,
                "totalDamageDealtToChampions": 24737,
                "totalDamageTaken": 24637,
                "totalHeal": 3568,
                "totalMinionsKilled": 162,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 111,
                "totalUnitsHealed": 3,
                "tripleKills": 0,
                "trueDamageDealt": 1869,
                "trueDamageDealtToChampions": 847,
                "trueDamageTaken": 1320,
                "turretKills": 1,
                "unrealKills": 0,
                "visionScore": 11,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 0,
                "wardsPlaced": 8,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 4.9,
                    "10-20": 5.7,
                    "20-30": 5.6
                },
                "csDiffPerMinDeltas": {
                    "0-10": -0.34999999999999987,
                    "10-20": 0.25000000000000044,
                    "20-30": 1.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -204.2,
                    "10-20": 266.6000000000001,
                    "20-30": 446.59999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 400.9,
                    "10-20": 1059.3,
                    "20-30": 767
                },
                "goldPerMinDeltas": {
                    "0-10": 328.5,
                    "10-20": 559.8,
                    "20-30": 447
                },
                "lane": "BOTTOM",
                "participantId": 1,
                "role": "DUO_CARRY",
                "xpDiffPerMinDeltas": {
                    "0-10": 59.599999999999994,
                    "10-20": -13.050000000000011,
                    "20-30": 72.25
                },
                "xpPerMinDeltas": {
                    "0-10": 303.4,
                    "10-20": 508.1,
                    "20-30": 571.8
                }
            }
        },
        {
            "championId": 38,
            "participantId": 2,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "assists": 6,
                "champLevel": 14,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 3713,
                "damageDealtToTurrets": 1004,
                "damageSelfMitigated": 18288,
                "deaths": 8,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 10257,
                "goldSpent": 9025,
                "inhibitorKills": 0,
                "item0": 2033,
                "item1": 3157,
                "item2": 3040,
                "item3": 3047,
                "item4": 1058,
                "item5": 0,
                "item6": 3340,
                "killingSprees": 2,
                "kills": 6,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 468,
                "magicDamageDealt": 69820,
                "magicDamageDealtToChampions": 10777,
                "magicalDamageTaken": 9693,
                "neutralMinionsKilled": 8,
                "neutralMinionsKilledEnemyJungle": 0,
                "neutralMinionsKilledTeamJungle": 5,
                "objectivePlayerScore": 0,
                "participantId": 2,
                "pentaKills": 0,
                "perk0": 8021,
                "perk0Var1": 2334,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 3533,
                "perk1Var2": 500,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 15,
                "perk2Var2": 50,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 372,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 829,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 2547,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "physicalDamageDealt": 15265,
                "physicalDamageDealtToChampions": 1018,
                "physicalDamageTaken": 12960,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5003,
                "timeCCingOthers": 13,
                "totalDamageDealt": 85958,
                "totalDamageDealtToChampions": 12435,
                "totalDamageTaken": 22886,
                "totalHeal": 5752,
                "totalMinionsKilled": 136,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 108,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 871,
                "trueDamageDealtToChampions": 639,
                "trueDamageTaken": 232,
                "turretKills": 1,
                "unrealKills": 0,
                "visionScore": 8,
                "visionWardsBoughtInGame": 1,
                "wardsKilled": 0,
                "wardsPlaced": 6,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 5.9,
                    "10-20": 3.5,
                    "20-30": 4.1
                },
                "csDiffPerMinDeltas": {
                    "0-10": -1.5999999999999999,
                    "10-20": -1.4,
                    "20-30": -1.0999999999999996
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 140.69999999999996,
                    "10-20": -290.5,
                    "20-30": -452.30000000000007
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 372,
                    "10-20": 957.6,
                    "20-30": 757.4
                },
                "goldPerMinDeltas": {
                    "0-10": 257,
                    "10-20": 298.5,
                    "20-30": 400
                },
                "lane": "MIDDLE",
                "participantId": 2,
                "role": "SOLO",
                "xpDiffPerMinDeltas": {
                    "0-10": -47.900000000000034,
                    "10-20": -224.5,
                    "20-30": -94.99999999999997
                },
                "xpPerMinDeltas": {
                    "0-10": 403.7,
                    "10-20": 301.7,
                    "20-30": 525.4
                }
            }
        },
        {
            "championId": 104,
            "participantId": 3,
            "spell1Id": 11,
            "spell2Id": 4,
            "stats": {
                "assists": 11,
                "champLevel": 14,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 7137,
                "damageDealtToTurrets": 0,
                "damageSelfMitigated": 16713,
                "deaths": 10,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 10825,
                "goldSpent": 10675,
                "inhibitorKills": 0,
                "item0": 3142,
                "item1": 3812,
                "item2": 3047,
                "item3": 1400,
                "item4": 1029,
                "item5": 0,
                "item6": 3340,
                "killingSprees": 1,
                "kills": 5,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 3,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 465,
                "magicDamageDealt": 6255,
                "magicDamageDealtToChampions": 414,
                "magicalDamageTaken": 10493,
                "neutralMinionsKilled": 94,
                "neutralMinionsKilledEnemyJungle": 4,
                "neutralMinionsKilledTeamJungle": 69,
                "objectivePlayerScore": 0,
                "participantId": 3,
                "pentaKills": 0,
                "perk0": 8230,
                "perk0Var1": 17,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8275,
                "perk1Var1": 24,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8233,
                "perk2Var1": 20,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8232,
                "perk3Var1": 3,
                "perk3Var2": 10,
                "perk3Var3": 0,
                "perk4": 9111,
                "perk4Var1": 328,
                "perk4Var2": 320,
                "perk4Var3": 0,
                "perk5": 9105,
                "perk5Var1": 10,
                "perk5Var2": 30,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8000,
                "physicalDamageDealt": 112743,
                "physicalDamageDealtToChampions": 16408,
                "physicalDamageTaken": 12316,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 22,
                "totalDamageDealt": 127917,
                "totalDamageDealtToChampions": 18431,
                "totalDamageTaken": 24045,
                "totalHeal": 4834,
                "totalMinionsKilled": 45,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 416,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 8918,
                "trueDamageDealtToChampions": 1608,
                "trueDamageTaken": 1235,
                "turretKills": 0,
                "unrealKills": 0,
                "visionScore": 21,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 1,
                "wardsPlaced": 10,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 0.4,
                    "10-20": 1,
                    "20-30": 2.3
                },
                "csDiffPerMinDeltas": {
                    "0-10": -0.09999999999999998,
                    "10-20": -0.6,
                    "20-30": -1.3000000000000003
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -235.4,
                    "10-20": -509.09999999999997,
                    "20-30": -1291.4
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 499.1,
                    "10-20": 889.4000000000001,
                    "20-30": 800.1
                },
                "goldPerMinDeltas": {
                    "0-10": 314.6,
                    "10-20": 314,
                    "20-30": 380.8
                },
                "lane": "JUNGLE",
                "participantId": 3,
                "role": "NONE",
                "xpDiffPerMinDeltas": {
                    "0-10": -115,
                    "10-20": -155.20000000000002,
                    "20-30": -130.40000000000003
                },
                "xpPerMinDeltas": {
                    "0-10": 264.1,
                    "10-20": 413.6,
                    "20-30": 499.5
                }
            }
        },
        {
            "championId": 23,
            "participantId": 4,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "assists": 2,
                "champLevel": 16,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 19469,
                "damageDealtToTurrets": 6274,
                "damageSelfMitigated": 31330,
                "deaths": 8,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": true,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 12078,
                "goldSpent": 11960,
                "inhibitorKills": 1,
                "item0": 2003,
                "item1": 3095,
                "item2": 3508,
                "item3": 3031,
                "item4": 3047,
                "item5": 0,
                "item6": 3340,
                "killingSprees": 1,
                "kills": 5,
                "largestCriticalStrike": 1567,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 369,
                "magicDamageDealt": 2984,
                "magicDamageDealtToChampions": 374,
                "magicalDamageTaken": 6265,
                "neutralMinionsKilled": 18,
                "neutralMinionsKilledEnemyJungle": 5,
                "neutralMinionsKilledTeamJungle": 8,
                "objectivePlayerScore": 0,
                "participantId": 4,
                "pentaKills": 0,
                "perk0": 8008,
                "perk0Var1": 1,
                "perk0Var2": 40,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 1146,
                "perk1Var2": 140,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 19,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 1109,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 11,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8210,
                "perk5Var1": 0,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "physicalDamageDealt": 162247,
                "physicalDamageDealtToChampions": 14760,
                "physicalDamageTaken": 24923,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 6,
                "totalDamageDealt": 174747,
                "totalDamageDealtToChampions": 17343,
                "totalDamageTaken": 31987,
                "totalHeal": 9225,
                "totalMinionsKilled": 184,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 53,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 9515,
                "trueDamageDealtToChampions": 2208,
                "trueDamageTaken": 798,
                "turretKills": 3,
                "unrealKills": 0,
                "visionScore": 17,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 1,
                "wardsPlaced": 10,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 5.1,
                    "10-20": 7.6,
                    "20-30": 5.7
                },
                "csDiffPerMinDeltas": {
                    "0-10": -1.4000000000000004,
                    "10-20": -1.5000000000000004,
                    "20-30": 0
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 171.19999999999996,
                    "10-20": -99.90000000000003,
                    "20-30": -618.3000000000001
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 658.7,
                    "10-20": 1316.5,
                    "20-30": 1096.4
                },
                "goldPerMinDeltas": {
                    "0-10": 242.5,
                    "10-20": 537.1,
                    "20-30": 367
                },
                "lane": "TOP",
                "participantId": 4,
                "role": "SOLO",
                "xpDiffPerMinDeltas": {
                    "0-10": 1.9000000000000057,
                    "10-20": -118.80000000000004,
                    "20-30": -46.39999999999998
                },
                "xpPerMinDeltas": {
                    "0-10": 465.3,
                    "10-20": 593.1,
                    "20-30": 506.5
                }
            }
        },
        {
            "championId": 63,
            "participantId": 5,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "assists": 15,
                "champLevel": 14,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 605,
                "damageDealtToTurrets": 605,
                "damageSelfMitigated": 10879,
                "deaths": 7,
                "doubleKills": 1,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 12461,
                "goldSpent": 11450,
                "inhibitorKills": 0,
                "item0": 3027,
                "item1": 3020,
                "item2": 3853,
                "item3": 3151,
                "item4": 3165,
                "item5": 1026,
                "item6": 3340,
                "killingSprees": 4,
                "kills": 10,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 3,
                "largestMultiKill": 2,
                "longestTimeSpentLiving": 813,
                "magicDamageDealt": 74292,
                "magicDamageDealtToChampions": 33173,
                "magicalDamageTaken": 12812,
                "neutralMinionsKilled": 7,
                "neutralMinionsKilledEnemyJungle": 0,
                "neutralMinionsKilledTeamJungle": 7,
                "objectivePlayerScore": 0,
                "participantId": 5,
                "pentaKills": 0,
                "perk0": 8128,
                "perk0Var1": 2824,
                "perk0Var2": 30,
                "perk0Var3": 0,
                "perk1": 8126,
                "perk1Var1": 872,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8120,
                "perk2Var1": 5,
                "perk2Var2": 30,
                "perk2Var3": 14,
                "perk3": 8106,
                "perk3Var1": 5,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8347,
                "perk5Var1": 0,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8300,
                "physicalDamageDealt": 3102,
                "physicalDamageDealtToChampions": 1401,
                "physicalDamageTaken": 13325,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5007,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 33,
                "totalDamageDealt": 80643,
                "totalDamageDealtToChampions": 37823,
                "totalDamageTaken": 26231,
                "totalHeal": 3263,
                "totalMinionsKilled": 36,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 84,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 3248,
                "trueDamageDealtToChampions": 3248,
                "trueDamageTaken": 94,
                "turretKills": 0,
                "unrealKills": 0,
                "visionScore": 50,
                "visionWardsBoughtInGame": 2,
                "wardsKilled": 3,
                "wardsPlaced": 27,
                "win": false
            },
            "teamId": 100,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 0.6,
                    "10-20": 0.30000000000000004,
                    "20-30": 2.7
                },
                "csDiffPerMinDeltas": {
                    "0-10": -0.34999999999999987,
                    "10-20": 0.25000000000000044,
                    "20-30": 1.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -204.2,
                    "10-20": 266.6000000000001,
                    "20-30": 446.59999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 280.3,
                    "10-20": 878.7,
                    "20-30": 1263.8
                },
                "goldPerMinDeltas": {
                    "0-10": 298.4,
                    "10-20": 402.1,
                    "20-30": 482.7
                },
                "lane": "BOTTOM",
                "participantId": 5,
                "role": "DUO_SUPPORT",
                "xpDiffPerMinDeltas": {
                    "0-10": 59.599999999999994,
                    "10-20": -13.050000000000011,
                    "20-30": 72.25
                },
                "xpPerMinDeltas": {
                    "0-10": 266.79999999999995,
                    "10-20": 403.70000000000005,
                    "20-30": 575.8
                }
            }
        },
        {
            "championId": 222,
            "participantId": 6,
            "spell1Id": 7,
            "spell2Id": 4,
            "stats": {
                "assists": 10,
                "champLevel": 15,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 13690,
                "damageDealtToTurrets": 7447,
                "damageSelfMitigated": 9547,
                "deaths": 9,
                "doubleKills": 1,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 11574,
                "goldSpent": 10375,
                "inhibitorKills": 1,
                "item0": 3006,
                "item1": 3031,
                "item2": 3508,
                "item3": 3123,
                "item4": 1036,
                "item5": 1036,
                "item6": 3363,
                "killingSprees": 2,
                "kills": 5,
                "largestCriticalStrike": 838,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "longestTimeSpentLiving": 276,
                "magicDamageDealt": 1628,
                "magicDamageDealtToChampions": 285,
                "magicalDamageTaken": 8766,
                "neutralMinionsKilled": 21,
                "neutralMinionsKilledEnemyJungle": 0,
                "neutralMinionsKilledTeamJungle": 16,
                "objectivePlayerScore": 0,
                "participantId": 6,
                "pentaKills": 0,
                "perk0": 8008,
                "perk0Var1": 2,
                "perk0Var2": 30,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 427,
                "perk1Var2": 300,
                "perk1Var3": 0,
                "perk2": 9103,
                "perk2Var1": 26,
                "perk2Var2": 10,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 398,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 10,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 28,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "physicalDamageDealt": 137992,
                "physicalDamageDealtToChampions": 14953,
                "physicalDamageTaken": 12302,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 16,
                "totalDamageDealt": 141614,
                "totalDamageDealtToChampions": 15579,
                "totalDamageTaken": 21721,
                "totalHeal": 3265,
                "totalMinionsKilled": 146,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 107,
                "totalUnitsHealed": 3,
                "tripleKills": 0,
                "trueDamageDealt": 1992,
                "trueDamageDealtToChampions": 340,
                "trueDamageTaken": 652,
                "turretKills": 3,
                "unrealKills": 0,
                "visionScore": 21,
                "visionWardsBoughtInGame": 1,
                "wardsKilled": 2,
                "wardsPlaced": 8,
                "win": true
            },
            "teamId": 200,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 5,
                    "10-20": 4.2,
                    "20-30": 4.7
                },
                "csDiffPerMinDeltas": {
                    "0-10": 0.34999999999999987,
                    "10-20": -0.25000000000000044,
                    "20-30": -1.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 204.2,
                    "10-20": -266.6000000000001,
                    "20-30": -446.59999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 634.5,
                    "10-20": 730.3,
                    "20-30": 721.2
                },
                "goldPerMinDeltas": {
                    "0-10": 215.5,
                    "10-20": 332,
                    "20-30": 508.9
                },
                "lane": "BOTTOM",
                "participantId": 6,
                "role": "DUO_CARRY",
                "xpDiffPerMinDeltas": {
                    "0-10": -59.599999999999994,
                    "10-20": 13.050000000000011,
                    "20-30": -72.25
                },
                "xpPerMinDeltas": {
                    "0-10": 264.8,
                    "10-20": 468.6,
                    "20-30": 633.8
                }
            }
        },
        {
            "championId": 58,
            "participantId": 7,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "assists": 8,
                "champLevel": 18,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 11454,
                "damageDealtToTurrets": 9814,
                "damageSelfMitigated": 45011,
                "deaths": 4,
                "doubleKills": 2,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 17357,
                "goldSpent": 15575,
                "inhibitorKills": 2,
                "item0": 3153,
                "item1": 3812,
                "item2": 3047,
                "item3": 3026,
                "item4": 3071,
                "item5": 3052,
                "item6": 3340,
                "killingSprees": 4,
                "kills": 12,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 5,
                "largestMultiKill": 2,
                "longestTimeSpentLiving": 618,
                "magicDamageDealt": 7226,
                "magicDamageDealtToChampions": 2684,
                "magicalDamageTaken": 11197,
                "neutralMinionsKilled": 15,
                "neutralMinionsKilledEnemyJungle": 13,
                "neutralMinionsKilledTeamJungle": 0,
                "objectivePlayerScore": 0,
                "participantId": 7,
                "pentaKills": 0,
                "perk0": 8005,
                "perk0Var1": 3530,
                "perk0Var2": 2158,
                "perk0Var3": 1372,
                "perk1": 9111,
                "perk1Var1": 1996,
                "perk1Var2": 400,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 13,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 1245,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8446,
                "perk4Var1": 3710,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8473,
                "perk5Var1": 758,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8400,
                "physicalDamageDealt": 185089,
                "physicalDamageDealtToChampions": 30809,
                "physicalDamageTaken": 22345,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002,
                "timeCCingOthers": 40,
                "totalDamageDealt": 196987,
                "totalDamageDealtToChampions": 34920,
                "totalDamageTaken": 39004,
                "totalHeal": 16784,
                "totalMinionsKilled": 216,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 157,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 4672,
                "trueDamageDealtToChampions": 1426,
                "trueDamageTaken": 5461,
                "turretKills": 5,
                "unrealKills": 0,
                "visionScore": 29,
                "visionWardsBoughtInGame": 1,
                "wardsKilled": 1,
                "wardsPlaced": 9,
                "win": true
            },
            "teamId": 200,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 6.5,
                    "10-20": 9.100000000000001,
                    "20-30": 5.7
                },
                "csDiffPerMinDeltas": {
                    "0-10": 1.4000000000000004,
                    "10-20": 1.5000000000000004,
                    "20-30": 0
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -171.19999999999996,
                    "10-20": 99.90000000000003,
                    "20-30": 618.3000000000001
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 487.5,
                    "10-20": 1416.4,
                    "20-30": 1714.7
                },
                "goldPerMinDeltas": {
                    "0-10": 348.9,
                    "10-20": 680.7,
                    "20-30": 528.3
                },
                "lane": "TOP",
                "participantId": 7,
                "role": "SOLO",
                "xpDiffPerMinDeltas": {
                    "0-10": -1.9000000000000057,
                    "10-20": 118.80000000000004,
                    "20-30": 46.39999999999998
                },
                "xpPerMinDeltas": {
                    "0-10": 463.4,
                    "10-20": 711.9000000000001,
                    "20-30": 552.9
                }
            }
        },
        {
            "championId": 19,
            "participantId": 8,
            "spell1Id": 4,
            "spell2Id": 11,
            "stats": {
                "assists": 10,
                "champLevel": 17,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 30781,
                "damageDealtToTurrets": 3528,
                "damageSelfMitigated": 37689,
                "deaths": 9,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": true,
                "firstTowerKill": false,
                "goldEarned": 14872,
                "goldSpent": 13573,
                "inhibitorKills": 0,
                "item0": 1401,
                "item1": 3153,
                "item2": 3077,
                "item3": 3111,
                "item4": 3082,
                "item5": 3078,
                "item6": 3340,
                "killingSprees": 2,
                "kills": 9,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 479,
                "magicDamageDealt": 48393,
                "magicDamageDealtToChampions": 9848,
                "magicalDamageTaken": 11903,
                "neutralMinionsKilled": 131,
                "neutralMinionsKilledEnemyJungle": 27,
                "neutralMinionsKilledTeamJungle": 60,
                "objectivePlayerScore": 0,
                "participantId": 8,
                "pentaKills": 0,
                "perk0": 8005,
                "perk0Var1": 1641,
                "perk0Var2": 892,
                "perk0Var3": 748,
                "perk1": 9111,
                "perk1Var1": 1471,
                "perk1Var2": 380,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 10,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 855,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8234,
                "perk4Var1": 12162,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8232,
                "perk5Var1": 5,
                "perk5Var2": 20,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "physicalDamageDealt": 130787,
                "physicalDamageDealtToChampions": 12283,
                "physicalDamageTaken": 32660,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001,
                "timeCCingOthers": 36,
                "totalDamageDealt": 203681,
                "totalDamageDealtToChampions": 22673,
                "totalDamageTaken": 46203,
                "totalHeal": 22624,
                "totalMinionsKilled": 67,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 214,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 24500,
                "trueDamageDealtToChampions": 542,
                "trueDamageTaken": 1638,
                "turretKills": 1,
                "unrealKills": 0,
                "visionScore": 20,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 0,
                "wardsPlaced": 8,
                "win": true
            },
            "teamId": 200,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 0.5,
                    "10-20": 1.6,
                    "20-30": 3.6
                },
                "csDiffPerMinDeltas": {
                    "0-10": 0.09999999999999998,
                    "10-20": 0.6,
                    "20-30": 1.3000000000000003
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 235.4,
                    "10-20": 509.09999999999997,
                    "20-30": 1291.4
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 734.5,
                    "10-20": 1398.5,
                    "20-30": 2091.5
                },
                "goldPerMinDeltas": {
                    "0-10": 394.9,
                    "10-20": 437.6,
                    "20-30": 481.2
                },
                "lane": "JUNGLE",
                "participantId": 8,
                "role": "NONE",
                "xpDiffPerMinDeltas": {
                    "0-10": 115,
                    "10-20": 155.20000000000002,
                    "20-30": 130.40000000000003
                },
                "xpPerMinDeltas": {
                    "0-10": 379.1,
                    "10-20": 568.8,
                    "20-30": 629.9000000000001
                }
            }
        },
        {
            "championId": 69,
            "participantId": 9,
            "spell1Id": 4,
            "spell2Id": 21,
            "stats": {
                "assists": 8,
                "champLevel": 16,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 20435,
                "damageDealtToTurrets": 5333,
                "damageSelfMitigated": 14634,
                "deaths": 6,
                "doubleKills": 3,
                "firstBloodAssist": false,
                "firstBloodKill": true,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 15024,
                "goldSpent": 13785,
                "inhibitorKills": 0,
                "item0": 3151,
                "item1": 3040,
                "item2": 3089,
                "item3": 3116,
                "item4": 1052,
                "item5": 0,
                "item6": 3340,
                "killingSprees": 3,
                "kills": 13,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 6,
                "largestMultiKill": 2,
                "longestTimeSpentLiving": 659,
                "magicDamageDealt": 159437,
                "magicDamageDealtToChampions": 25760,
                "magicalDamageTaken": 12908,
                "neutralMinionsKilled": 27,
                "neutralMinionsKilledEnemyJungle": 12,
                "neutralMinionsKilledTeamJungle": 9,
                "objectivePlayerScore": 0,
                "participantId": 9,
                "pentaKills": 0,
                "perk0": 8010,
                "perk0Var1": 579,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 4534,
                "perk1Var2": 500,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 14,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 550,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 1510,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 6921,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "physicalDamageDealt": 9087,
                "physicalDamageDealtToChampions": 713,
                "physicalDamageTaken": 13958,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5003,
                "timeCCingOthers": 23,
                "totalDamageDealt": 170663,
                "totalDamageDealtToChampions": 26606,
                "totalDamageTaken": 27794,
                "totalHeal": 13786,
                "totalMinionsKilled": 178,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 724,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 2137,
                "trueDamageDealtToChampions": 131,
                "trueDamageTaken": 927,
                "turretKills": 2,
                "unrealKills": 0,
                "visionScore": 13,
                "visionWardsBoughtInGame": 0,
                "wardsKilled": 0,
                "wardsPlaced": 8,
                "win": true
            },
            "teamId": 200,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 7.5,
                    "10-20": 4.9,
                    "20-30": 5.199999999999999
                },
                "csDiffPerMinDeltas": {
                    "0-10": 1.5999999999999999,
                    "10-20": 1.4,
                    "20-30": 1.0999999999999996
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -140.69999999999996,
                    "10-20": 290.5,
                    "20-30": 452.30000000000007
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 231.3,
                    "10-20": 1248.1,
                    "20-30": 1209.7
                },
                "goldPerMinDeltas": {
                    "0-10": 327.5,
                    "10-20": 610.4,
                    "20-30": 482.4
                },
                "lane": "MIDDLE",
                "participantId": 9,
                "role": "SOLO",
                "xpDiffPerMinDeltas": {
                    "0-10": 47.900000000000034,
                    "10-20": 224.5,
                    "20-30": 94.99999999999997
                },
                "xpPerMinDeltas": {
                    "0-10": 451.6,
                    "10-20": 526.2,
                    "20-30": 620.4
                }
            }
        },
        {
            "championId": 111,
            "participantId": 10,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "assists": 6,
                "champLevel": 13,
                "combatPlayerScore": 0,
                "damageDealtToObjectives": 2803,
                "damageDealtToTurrets": 1393,
                "damageSelfMitigated": 26610,
                "deaths": 8,
                "doubleKills": 0,
                "firstBloodAssist": false,
                "firstBloodKill": false,
                "firstInhibitorAssist": false,
                "firstInhibitorKill": false,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "goldEarned": 8122,
                "goldSpent": 7170,
                "inhibitorKills": 0,
                "item0": 3860,
                "item1": 3117,
                "item2": 3742,
                "item3": 0,
                "item4": 0,
                "item5": 3109,
                "item6": 3364,
                "killingSprees": 1,
                "kills": 3,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "longestTimeSpentLiving": 536,
                "magicDamageDealt": 19129,
                "magicDamageDealtToChampions": 5502,
                "magicalDamageTaken": 7303,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "objectivePlayerScore": 0,
                "participantId": 10,
                "pentaKills": 0,
                "perk0": 8439,
                "perk0Var1": 565,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8401,
                "perk1Var1": 415,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8473,
                "perk2Var1": 495,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 192,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8347,
                "perk5Var1": 0,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8300,
                "physicalDamageDealt": 8693,
                "physicalDamageDealtToChampions": 2067,
                "physicalDamageTaken": 8094,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "quadraKills": 0,
                "sightWardsBoughtInGame": 0,
                "statPerk0": 5007,
                "statPerk1": 5002,
                "statPerk2": 5002,
                "timeCCingOthers": 54,
                "totalDamageDealt": 33626,
                "totalDamageDealtToChampions": 8790,
                "totalDamageTaken": 16209,
                "totalHeal": 2035,
                "totalMinionsKilled": 34,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "totalTimeCrowdControlDealt": 296,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 5803,
                "trueDamageDealtToChampions": 1220,
                "trueDamageTaken": 811,
                "turretKills": 0,
                "unrealKills": 0,
                "visionScore": 53,
                "visionWardsBoughtInGame": 4,
                "wardsKilled": 5,
                "wardsPlaced": 24,
                "win": true
            },
            "teamId": 200,
            "timeline": {
                "creepsPerMinDeltas": {
                    "0-10": 1.2000000000000002,
                    "10-20": 1.2999999999999998,
                    "20-30": 0.8
                },
                "csDiffPerMinDeltas": {
                    "0-10": 0.34999999999999987,
                    "10-20": -0.25000000000000044,
                    "20-30": -1.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 204.2,
                    "10-20": -266.6000000000001,
                    "20-30": -446.59999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 455.09999999999997,
                    "10-20": 674.5,
                    "20-30": 416.4
                },
                "goldPerMinDeltas": {
                    "0-10": 179.1,
                    "10-20": 283.1,
                    "20-30": 263.4
                },
                "lane": "BOTTOM",
                "participantId": 10,
                "role": "DUO_SUPPORT",
                "xpDiffPerMinDeltas": {
                    "0-10": -59.599999999999994,
                    "10-20": 13.050000000000011,
                    "20-30": -72.25
                },
                "xpPerMinDeltas": {
                    "0-10": 186.2,
                    "10-20": 469.3,
                    "20-30": 369.3
                }
            }
        }
    ],
    "teams": [
        {
            "bans": [
                {
                    "championId": 122,
                    "pickTurn": 1
                },
                {
                    "championId": 67,
                    "pickTurn": 2
                },
                {
                    "championId": 50,
                    "pickTurn": 3
                },
                {
                    "championId": 141,
                    "pickTurn": 4
                },
                {
                    "championId": 105,
                    "pickTurn": 5
                }
            ],
            "baronKills": 0,
            "dominionVictoryScore": 0,
            "dragonKills": 1,
            "firstBaron": false,
            "firstBlood": false,
            "firstDragon": false,
            "firstInhibitor": true,
            "firstRiftHerald": false,
            "firstTower": false,
            "inhibitorKills": 1,
            "riftHeraldKills": 1,
            "teamId": 100,
            "towerKills": 6,
            "vilemawKills": 0,
            "win": "Fail"
        },
        {
            "bans": [
                {
                    "championId": 157,
                    "pickTurn": 6
                },
                {
                    "championId": 24,
                    "pickTurn": 7
                },
                {
                    "championId": 53,
                    "pickTurn": 8
                },
                {
                    "championId": 875,
                    "pickTurn": 9
                },
                {
                    "championId": 67,
                    "pickTurn": 10
                }
            ],
            "baronKills": 1,
            "dominionVictoryScore": 0,
            "dragonKills": 4,
            "firstBaron": true,
            "firstBlood": true,
            "firstDragon": true,
            "firstInhibitor": false,
            "firstRiftHerald": true,
            "firstTower": true,
            "inhibitorKills": 3,
            "riftHeraldKills": 1,
            "teamId": 200,
            "towerKills": 11,
            "vilemawKills": 0,
            "win": "Win"
        }
    ]
}